### ISSUE TITLE
Refuge Dataset

### ISSUE THREAD

**Issue by qianqianCDQ** [EmmaW8/BEAL#4]
Hello, I am more interested in your code, but among the three datasets, the refuge dataset is not available for download right now. Do you have a ready-made dataset?

**Comment by hitxiaoting** [comment]
Thanks for your sharing. Would you like to share the data set, because the REFUGEdataset is not available now.

**Comment by EmmaW8** [comment]
REFUGE dataset can be downloaded from here:
https://ai.baidu.com/broad/download?dataset=gon
