### ISSUE TITLE
how to process valid dataset

### ISSUE THREAD

**Issue by lulujiang1281** [EmmaW8/BEAL#5]
When processing target domain dataset(Drishti-GS or RIM-ONE-r3), the mask is different from REFUGE dataset. How to process it? Did you have preprocessing steps? Thanks so much!!!

**Comment by EmmaW8** [comment]
I have updated the details in the readme. Please download the data from https://drive.google.com/file/d/1B7ArHRBjt2Dx29a3A6X_lGhD0vDVr3sy/view .
