### ISSUE TITLE
weight file appears to be corrupted?

### ISSUE THREAD

**Issue by JACKYLUO1991** [EmmaW8/BEAL#6]
Thanks for your work. There was a problem with downloading the weights. Is it now possible to download the weights? Or is it my network transmission? I look forward to hearing from you...

**Comment by JACKYLUO1991** [comment]
And why +1 in utils/Utils.py in line 110?

**Comment by EmmaW8** [comment]
After label, the background is set as 0. The regiosn in the foreground will be set as 1,2,3...
But the area id is from 0.
The background is already 0. We only need to set other non-largest areas to be 0.

**Comment by JACKYLUO1991** [comment]
thanks

**Comment by EmmaW8** [comment]
Have you downloaded the weight files sucessful?
The weights are stored in Google drive. If you are in mainland, you may need VPN to access it.

**Comment by JACKYLUO1991** [comment]
@EmmaW8 I can download, but the weight file is damaged, it doesn't matter, I have retrained a version, thank you for your guidance.
