### ISSUE TITLE
512 or 800?

### ISSUE THREAD

**Issue by JACKYLUO1991** [EmmaW8/BEAL#7]
I am very sorry, but there is still a problem that bothers me. The input of the test.py script is 800 and Rescale is not executed. Will this affect the results?

**Comment by EmmaW8** [comment]
Our segmentation network is end-to-end and full of convolutional layers.
So it could handle different sizes of images.

The random scale is a way of data augmentation and only have 50% chance to perform random scale.
The remaining images are not rescaled, so our network can handle the test image without scale with different input size.

**Comment by JACKYLUO1991** [comment]
thx...
