### ISSUE TITLE
REFUGE2018 Glaucoma validation set label

### ISSUE THREAD

**Issue by JACKYLUO1991** [EmmaW8/BEAL#8]
Hello, do you mind giving the groundtruth of the REFUGE2018 Glaucoma validation set, the link to Baidu Brain is broken.

**Comment by EmmaW8** [comment]
Sorry for the delay.
You may download the dataset from this link: https://drive.google.com/file/d/1B7ArHRBjt2Dx29a3A6X_lGhD0vDVr3sy/view.
Domain 4 is the validation dataset of REFUGE.

**Comment by JACKYLUO1991** [comment]
@EmmaW8 Zhu told me to register for the refuge2 competition and get data labels by the way. Thank you anyway...
